/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connect dbsetting;
    String driver, database, user, pass;
    Object tableTablean;

    public Login() {
        initComponents();

        dbsetting = new Connect();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        Login = new javax.swing.JPanel();
        pane_login = new javax.swing.JPanel();
        labelLogin = new javax.swing.JLabel();
        panelFormLogin = new PanelRound();
        labelLoginEmail = new javax.swing.JLabel();
        textLoginEmail = new TextFieldRound();
        labeLoginlPassword = new javax.swing.JLabel();
        textLoginPassword = new PasswordFieldRound();
        checkLoginShowPassword = new javax.swing.JCheckBox();
        buttonToRegister = new ButtonRound();
        buttonLogin = new ButtonRound();
        Register = new javax.swing.JPanel();
        pane_title1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pane_register = new javax.swing.JPanel();
        labelRegister = new javax.swing.JLabel();
        panelFormRegister = new PanelRound();
        labelRegisterEmail = new javax.swing.JLabel();
        textRegisterEmail = new TextFieldRound();
        labelRegisterPassword = new javax.swing.JLabel();
        textRegisterPassword = new PasswordFieldRound();
        checkRegisterShowPassword = new javax.swing.JCheckBox();
        labelGender = new javax.swing.JLabel();
        radioGenderMale = new javax.swing.JRadioButton();
        radioGenderFemale = new javax.swing.JRadioButton();
        buttonToLogin = new ButtonRound();
        buttonRegister = new ButtonRound();
        pane_title = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setBackground(new java.awt.Color(22, 25, 32));
        Login.setPreferredSize(new java.awt.Dimension(1280, 720));

        pane_login.setBackground(new java.awt.Color(22, 25, 32));
        pane_login.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pane_login.setPreferredSize(new java.awt.Dimension(640, 720));
        pane_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogin.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(255, 255, 255));
        labelLogin.setText("LOGIN");
        pane_login.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 144, -1, -1));

        labelLoginEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelLoginEmail.setForeground(new java.awt.Color(4, 175, 244));
        labelLoginEmail.setText("Email");

        labeLoginlPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labeLoginlPassword.setForeground(new java.awt.Color(4, 175, 244));
        labeLoginlPassword.setText("Password");

        checkLoginShowPassword.setBackground(new java.awt.Color(32, 49, 69));
        checkLoginShowPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkLoginShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        checkLoginShowPassword.setText("Show Password");
        checkLoginShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLoginShowPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormLoginLayout = new javax.swing.GroupLayout(panelFormLogin);
        panelFormLogin.setLayout(panelFormLoginLayout);
        panelFormLoginLayout.setHorizontalGroup(
            panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLoginLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkLoginShowPassword)
                    .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                        .addComponent(textLoginEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelLoginEmail)
                        .addComponent(labeLoginlPassword)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelFormLoginLayout.setVerticalGroup(
            panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelLoginEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labeLoginlPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkLoginShowPassword)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pane_login.add(panelFormLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 234, -1, -1));

        buttonToRegister.setBackground(new java.awt.Color(22, 25, 32));
        buttonToRegister.setForeground(new java.awt.Color(103, 193, 245));
        buttonToRegister.setText("Don't have an account?");
        buttonToRegister.setBorderColor(new java.awt.Color(22, 25, 32));
        buttonToRegister.setColor(new java.awt.Color(22, 25, 32));
        buttonToRegister.setColorClick(new java.awt.Color(22, 12, 18));
        buttonToRegister.setColorOver(new java.awt.Color(22, 52, 84));
        buttonToRegister.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        buttonToRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToRegisterActionPerformed(evt);
            }
        });
        pane_login.add(buttonToRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 509, -1, -1));

        buttonLogin.setBackground(new java.awt.Color(0, 96, 213));
        buttonLogin.setText("LOGIN");
        buttonLogin.setBorderColor(new java.awt.Color(0, 96, 213));
        buttonLogin.setColor(new java.awt.Color(0, 96, 213));
        buttonLogin.setColorClick(new java.awt.Color(0, 45, 210));
        buttonLogin.setColorOver(new java.awt.Color(0, 148, 206));
        buttonLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        pane_login.add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 571, 156, 51));

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(pane_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pane_login, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabbedPane.addTab("tab1", Login);

        Register.setBackground(new java.awt.Color(22, 25, 32));
        Register.setPreferredSize(new java.awt.Dimension(1280, 720));

        pane_title1.setBackground(new java.awt.Color(0, 0, 0));
        pane_title1.setPreferredSize(new java.awt.Dimension(640, 720));
        pane_title1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GAME STORE");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        pane_title1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 330, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAME STORE COVER.png"))); // NOI18N
        jLabel3.setFocusable(false);
        pane_title1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 620, 720));

        pane_register.setBackground(new java.awt.Color(22, 25, 32));
        pane_register.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pane_register.setPreferredSize(new java.awt.Dimension(640, 720));
        pane_register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRegister.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelRegister.setForeground(new java.awt.Color(255, 255, 255));
        labelRegister.setText("REGISTER");
        pane_register.add(labelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 111, -1, -1));

        labelRegisterEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelRegisterEmail.setForeground(new java.awt.Color(4, 175, 244));
        labelRegisterEmail.setText("Email");

        labelRegisterPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelRegisterPassword.setForeground(new java.awt.Color(4, 175, 244));
        labelRegisterPassword.setText("Password");

        checkRegisterShowPassword.setBackground(new java.awt.Color(32, 49, 69));
        checkRegisterShowPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkRegisterShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        checkRegisterShowPassword.setText("Show Password");
        checkRegisterShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRegisterShowPasswordActionPerformed(evt);
            }
        });

        labelGender.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelGender.setForeground(new java.awt.Color(4, 175, 244));
        labelGender.setText("Gender");

        radioGenderMale.setBackground(new java.awt.Color(32, 49, 69));
        radioGenderMale.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioGenderMale.setForeground(new java.awt.Color(255, 255, 255));
        radioGenderMale.setText("Male");

        radioGenderFemale.setBackground(new java.awt.Color(32, 49, 69));
        radioGenderFemale.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioGenderFemale.setForeground(new java.awt.Color(255, 255, 255));
        radioGenderFemale.setText("Female");

        javax.swing.GroupLayout panelFormRegisterLayout = new javax.swing.GroupLayout(panelFormRegister);
        panelFormRegister.setLayout(panelFormRegisterLayout);
        panelFormRegisterLayout.setHorizontalGroup(
            panelFormRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormRegisterLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelFormRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelFormRegisterLayout.createSequentialGroup()
                            .addComponent(labelGender)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkRegisterShowPassword))
                        .addComponent(textRegisterPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                        .addComponent(textRegisterEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelRegisterEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelRegisterPassword, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(panelFormRegisterLayout.createSequentialGroup()
                        .addComponent(radioGenderMale)
                        .addGap(99, 99, 99)
                        .addComponent(radioGenderFemale)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelFormRegisterLayout.setVerticalGroup(
            panelFormRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormRegisterLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelRegisterEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textRegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelRegisterPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textRegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelFormRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormRegisterLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkRegisterShowPassword))
                    .addGroup(panelFormRegisterLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(labelGender)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioGenderMale)
                    .addComponent(radioGenderFemale))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pane_register.add(panelFormRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 201, -1, -1));

        buttonToLogin.setBackground(new java.awt.Color(22, 25, 32));
        buttonToLogin.setForeground(new java.awt.Color(103, 193, 245));
        buttonToLogin.setText("Already have an account?");
        buttonToLogin.setBorderColor(new java.awt.Color(22, 25, 32));
        buttonToLogin.setColor(new java.awt.Color(22, 25, 32));
        buttonToLogin.setColorClick(new java.awt.Color(22, 12, 18));
        buttonToLogin.setColorOver(new java.awt.Color(22, 52, 84));
        buttonToLogin.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        buttonToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToLoginActionPerformed(evt);
            }
        });
        pane_register.add(buttonToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 550, -1, -1));

        buttonRegister.setText("REGISTER");
        buttonRegister.setBorderColor(new java.awt.Color(111, 166, 32));
        buttonRegister.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });
        pane_register.add(buttonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 587, 156, 51));

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addComponent(pane_title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pane_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane_title1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pane_register, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedPane.addTab("tab2", Register);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -50, 1300, 720));

        pane_title.setBackground(new java.awt.Color(0, 0, 0));
        pane_title.setPreferredSize(new java.awt.Dimension(640, 720));
        pane_title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GAME STORE");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        pane_title.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 330, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAME STORE COVER.png"))); // NOI18N
        pane_title.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        getContentPane().add(pane_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkLoginShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLoginShowPasswordActionPerformed
        if (checkLoginShowPassword.isSelected()) {
            textLoginPassword.setEchoChar((char) 0);
        } else {
            textLoginPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkLoginShowPasswordActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        try {
            Class.forName(driver);
            Connection conn = DriverManager.getConnection(database, user, pass);

            String email = textLoginEmail.getText();
            String password = textLoginPassword.getText();

            Statement stt = conn.createStatement();
            String SQL = "SELECT * FROM users WHERE email='" + email + "' AND name='" + password + "'";
            ResultSet res = stt.executeQuery(SQL);
            if (res.next()) {
                Dashboard dashboard = new Dashboard();
                dashboard.setVisible(true);
                this.setVisible(false);
            } else if (textLoginEmail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill out username");
            } else if (textLoginPassword.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill out password");
            } else if (textLoginEmail.getText().contains("admin@gmail.com") && textLoginPassword.getText().contains("Admin")) {
                Dashboard dashboard = new Dashboard();
                dashboard.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Wrong username or password!", "Message", JOptionPane.ERROR_MESSAGE);
            }
            conn.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonToRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToRegisterActionPerformed
        tabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_buttonToRegisterActionPerformed

    private void checkRegisterShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRegisterShowPasswordActionPerformed
        if (checkRegisterShowPassword.isSelected()) {
            textRegisterPassword.setEchoChar((char) 0);
        } else {
            textRegisterPassword.setEchoChar('*');
        }

    }//GEN-LAST:event_checkRegisterShowPasswordActionPerformed

    private void buttonToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToLoginActionPerformed
        tabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_buttonToLoginActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        String data[] = new String[3];
        try {
            Class.forName(driver);
            Connection conn = DriverManager.getConnection(database, user, pass);

            String email = textRegisterEmail.getText();
            String password = textRegisterPassword.getText();
            String gender = "";

            Statement stt = conn.createStatement();
            if (radioGenderMale.isSelected()) {
                gender = "male";
                System.out.println(gender);
            } else if (radioGenderFemale.isSelected()) {
                gender = "female";
                System.out.println(gender);
            } else {
                JOptionPane.showMessageDialog(null, "Please select your gender");
            }
            String SQL = "INSERT INTO users (name, "
                    + "email, gender) "
                    + "VALUES "
                    + "('" + password + "', "
                    + "'" + email + "', "
                    + "'" + gender + "')";
            stt.executeUpdate(SQL);
            String SQL2 = "SELECT * FROM users WHERE name='" + password + "'";
            ResultSet res = stt.executeQuery(SQL2);

            if (res.next()) {
                JOptionPane.showMessageDialog(null, "Data has been saved", "Saved", JOptionPane.INFORMATION_MESSAGE);
            } else if (textRegisterEmail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill out username");
            } else if (textRegisterPassword.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill out password");
            }

            conn.close();
            stt.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Register;
    private ButtonRound buttonLogin;
    private ButtonRound buttonRegister;
    private ButtonRound buttonToLogin;
    private ButtonRound buttonToRegister;
    private javax.swing.JCheckBox checkLoginShowPassword;
    private javax.swing.JCheckBox checkRegisterShowPassword;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labeLoginlPassword;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelLoginEmail;
    private javax.swing.JLabel labelRegister;
    private javax.swing.JLabel labelRegisterEmail;
    private javax.swing.JLabel labelRegisterPassword;
    private javax.swing.JPanel pane_login;
    private javax.swing.JPanel pane_register;
    private javax.swing.JPanel pane_title;
    private javax.swing.JPanel pane_title1;
    private PanelRound panelFormLogin;
    private PanelRound panelFormRegister;
    private javax.swing.JRadioButton radioGenderFemale;
    private javax.swing.JRadioButton radioGenderMale;
    private javax.swing.JTabbedPane tabbedPane;
    private TextFieldRound textLoginEmail;
    private PasswordFieldRound textLoginPassword;
    private TextFieldRound textRegisterEmail;
    private PasswordFieldRound textRegisterPassword;
    // End of variables declaration//GEN-END:variables
}
